# Generated by Django 4.0.5 on 2023-01-15 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('writer', models.ManyToManyField(to='sign.writer')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.writer')),
            ],
        ),
    ]
